In [1]:
import tensorflow as tf
import numpy as np

### Training and Test datasets

In [3]:
# Training data
x_data = [[1,2,1], [1,3,2], [1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1], [0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

In [6]:
# Evaluation our model using this test dataset
x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]]

In [16]:
X = tf.placeholder("float",[None,3])
Y = tf.placeholder("float",[None,3])
W = tf.Variable(tf.random_normal([3,3]), name="Weight")
b = tf.Variable(tf.random_normal([3]), name="bias")

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [18]:
# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict={X:x_data, Y:y_data})
        if step % 10 == 0:
            print(step, cost_val, W_val)
        
        
    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X:x_test}))
    # Calculate the accuracy
    print("Accuracy:", sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))

0 7.059932 [[ 2.5731013   0.18248442 -1.300221  ]
 [ 0.3084359  -0.22016734 -0.7529894 ]
 [-0.26412532  0.6877838  -1.4127742 ]]
10 1.8202595 [[ 2.2635245   0.12631996 -0.93448025]
 [-0.29049063 -0.57507074  0.20084053]
 [-0.657093    0.24552156 -0.5775443 ]]
20 1.5571804 [[ 2.0606534   0.13610053 -0.7413901 ]
 [-0.3207255  -0.52616256  0.1821673 ]
 [-0.5823025   0.19892348 -0.6057366 ]]
30 1.4086183 [[ 1.8726848   0.14342257 -0.56074345]
 [-0.32221025 -0.4919095   0.14939897]
 [-0.50689197  0.15987518 -0.6420989 ]]
40 1.2819703 [[ 1.6987628   0.14888117 -0.39228   ]
 [-0.31448358 -0.46563098  0.11539389]
 [-0.4451993   0.1300531  -0.67396945]]
50 1.17619 [[ 1.5399287   0.15258506 -0.23714979]
 [-0.3003818  -0.44471365  0.08037489]
 [-0.3953715   0.10701298 -0.700757  ]]
60 1.0889637 [[ 1.395982    0.15490477 -0.09552293]
 [-0.28239182 -0.427243    0.04491428]
 [-0.35525376  0.08869682 -0.7225586 ]]
70 1.0173452 [[ 1.2658281   0.15629166  0.03324401]
 [-0.26252595 -0.4119559   0.009761

### full_code

In [26]:
x_data = [[1,2,1], [1,3,2], [1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1], [0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]]

X = tf.placeholder("float",[None,3])
Y = tf.placeholder("float",[None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict={X:x_data, Y:y_data})
        if step % 100 == 0:
            print(step, cost_val, W_val)
        
    
    print("Prediction:", sess.run(prediction, feed_dict={X:x_test}))
    print("Accuracy:", sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))
    
# rate = 1 -> cost = 0.013679152 
# rate = 0.1 -> cost = 0.2728301
# rate = 0.01 -> cost = 0.58629334 
# rate = 0.01 -> cost = 1.7018555 

0 1.5793233 [[-0.64321715 -1.0559725  -1.0280048 ]
 [ 0.46306223 -0.880138    0.54053605]
 [-0.5917943   1.1246192  -0.47339115]]
100 0.7506838 [[-1.611712   -1.1251543   0.00967259]
 [ 0.13156858 -0.10311084  0.09500265]
 [ 0.1621108   0.39793155 -0.5006084 ]]
200 0.6235938 [[-2.1727214  -1.0790927   0.52462083]
 [ 0.1818332  -0.01683217 -0.04154035]
 [ 0.33324462  0.31629303 -0.59010315]]
300 0.5579488 [[-2.5917418  -1.0162222   0.8807692 ]
 [ 0.19740951  0.01017187 -0.08412047]
 [ 0.48026693  0.28190404 -0.7027365 ]]
400 0.5127663 [[-2.9435554  -0.950949    1.1673096 ]
 [ 0.19996555  0.02639582 -0.10290029]
 [ 0.6123311   0.25368178 -0.8065784 ]]
500 0.47797012 [[-3.2540812  -0.88768667  1.4145737 ]
 [ 0.19885619  0.03788684 -0.11328176]
 [ 0.73128384  0.22875099 -0.9006002 ]]
600 0.44965568 [[-3.5349407  -0.8281921   1.635939  ]
 [ 0.19682519  0.04661958 -0.11998321]
 [ 0.8394062   0.20655191 -0.98652303]]
700 0.42586473 [[-3.7926009  -0.77305114  1.8384587 ]
 [ 0.19474033  0.05353

### Learning rate: NaN

In [30]:
X = tf.placeholder("float",[None,3])
Y = tf.placeholder("float",[None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict={X:x_data, Y:y_data})
        if step % 100 == 0:
            print(step, cost_val, W_val)
        
    
    print("Prediction:", sess.run(prediction, feed_dict={X:x_test}))
    print("Accuracy:", sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))
    
# learning_rate =1.5 이면 rate가 너무커서 밖으로 나가버림
# learning_rate= 1e-10이면 rate가 너무 작아서 local minimize에 빠져버림 or 값이 더이상 줄어들지않음,
# cost가 계속 12.930634 

0 5.9301376 [[-0.32986513  0.8542019   0.11978465]
 [ 0.08357333  1.6030558  -0.7286192 ]
 [-0.8831898   0.07583113  1.2545645 ]]
100 5.9301376 [[-0.32986513  0.8542019   0.11978465]
 [ 0.08357333  1.6030558  -0.7286192 ]
 [-0.8831898   0.07583113  1.2545645 ]]
200 5.9301376 [[-0.32986513  0.8542019   0.11978465]
 [ 0.08357333  1.6030558  -0.7286192 ]
 [-0.8831898   0.07583113  1.2545645 ]]
300 5.9301376 [[-0.32986513  0.8542019   0.11978465]
 [ 0.08357333  1.6030558  -0.7286192 ]
 [-0.8831898   0.07583113  1.2545645 ]]
400 5.9301376 [[-0.32986513  0.8542019   0.11978465]
 [ 0.08357333  1.6030558  -0.7286192 ]
 [-0.8831898   0.07583113  1.2545645 ]]
500 5.9301376 [[-0.32986513  0.8542019   0.11978465]
 [ 0.08357333  1.6030558  -0.7286192 ]
 [-0.8831898   0.07583113  1.2545645 ]]
600 5.9301376 [[-0.32986513  0.8542019   0.11978465]
 [ 0.08357333  1.6030558  -0.7286192 ]
 [-0.8831898   0.07583113  1.2545645 ]]
700 5.9301376 [[-0.32986513  0.8542019   0.11978465]
 [ 0.08357333  1.6030558 

### Non-normalized inputs

In [32]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

# 중간중간에 909100, 1828100처럼 엄청 큰값들이 주어짐
# costfunction이 한쪽으로 치우치게 그래프가 그려짐

In [34]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [35]:
print(x_data.shape)
print(y_data.shape)

(8, 4)
(8, 1)


In [36]:
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [38]:
W = tf.Variable(tf.random_normal([4,1]))
b = tf.Variable(tf.random_normal([1]))

In [39]:
hypothesis = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [40]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [43]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    if step % 100 ==0:
        print(step, "cost:", cost_val, "\nPrediction:\n", hy_val)
        
# input data가 non-normalized 되어있기 때문에 cost값이 nan이 나옴

0 cost: 128197620000.0 
Prediction:
 [[-252444.83]
 [-506772.7 ]
 [-398950.5 ]
 [-280068.7 ]
 [-329835.84]
 [-332596.6 ]
 [-304940.4 ]
 [-387868.5 ]]
100 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
200 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
300 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
400 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
500 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
600 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
700 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
800 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
900 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1000 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]

### full_code

In [47]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4,1]))
b = tf.Variable(tf.random_normal([1]))

hypothesis = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    if step % 100 ==0:
        print(step, "cost:", cost_val, "\nPrediction:\n", hy_val)
        

0 cost: 785591040000.0 
Prediction:
 [[ 625614.75]
 [1259959.9 ]
 [ 991056.7 ]
 [ 694572.56]
 [ 818682.44]
 [ 825575.3 ]
 [ 756631.06]
 [ 963476.1 ]]
100 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
200 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
300 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
400 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
500 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
600 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
700 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
800 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
900 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1000 cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]

### Nromalized input (min-max scale)

In [64]:
from sklearn.preprocessing import MinMaxScaler

In [70]:
xy = [[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]]

In [73]:
xy=MinMaxScaler().fit_transform(xy)
print(xy)

[[1.         1.         0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881783 0.83755792]
 [0.54412549 0.50274824 0.57608696 0.60646801 0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.4258239  0.30434783 0.58504805 0.42624401]
 [0.49556179 0.4258239  0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [74]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4,1]))
b = tf.Variable(tf.random_normal([1]))

hypothesis = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    if step % 100 ==0:
        print(step, "cost:", cost_val, "\nPrediction:\n", hy_val)
        

0 cost: 0.8732122 
Prediction:
 [[-0.71325815]
 [-0.6464821 ]
 [-0.2214247 ]
 [ 0.25970787]
 [-0.04772151]
 [-0.00654906]
 [ 0.6214989 ]
 [ 0.61205757]]
100 cost: 0.86929834 
Prediction:
 [[-0.7094214 ]
 [-0.6429827 ]
 [-0.21856642]
 [ 0.2618417 ]
 [-0.04511005]
 [-0.00404894]
 [ 0.62295663]
 [ 0.6134231 ]]
200 cost: 0.86541593 
Prediction:
 [[-0.7056011 ]
 [-0.6394992 ]
 [-0.2157216 ]
 [ 0.26396602]
 [-0.04251033]
 [-0.00156009]
 [ 0.6244073 ]
 [ 0.6147818 ]]
300 cost: 0.86155844 
Prediction:
 [[-0.7017913 ]
 [-0.63602614]
 [-0.21288526]
 [ 0.26608306]
 [-0.0399189 ]
 [ 0.00092065]
 [ 0.625852  ]
 [ 0.6161345 ]]
400 cost: 0.85773104 
Prediction:
 [[-0.6979976 ]
 [-0.63256747]
 [-0.21006101]
 [ 0.26819098]
 [-0.0373385 ]
 [ 0.00339085]
 [ 0.62729037]
 [ 0.61748147]]
500 cost: 0.85392946 
Prediction:
 [[-0.694215  ]
 [-0.629121  ]
 [-0.20724684]
 [ 0.2702914 ]
 [-0.03476703]
 [ 0.00585234]
 [ 0.62872255]
 [ 0.61882174]]
600 cost: 0.85015655 
Prediction:
 [[-0.6904474 ]
 [-0.625688  ]
 [