In [22]:
import tensorflow as tf
import numpy as np

In [31]:
# def softmax(x):
#     e_x = np.exp(x - np.max(x))
#     return e_x / e_x.sum()

In [50]:
x_data = [[1,2,1,1], [2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]
# one-hot encoding

X = tf.placeholder("float",[None,4])
Y = tf.placeholder("float",[None,3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(Logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax((tf.matmul(X,W)+b))

# Cross entropy cost/loss
cost= tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X:x_data, Y:y_data})
        if step % 200 ==0 :
            print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}))


0 7.7723217
200 0.5792182
400 0.48423743
600 0.408037
800 0.33700353
1000 0.2656547
1200 0.23189959
1400 0.21112207
1600 0.19360672
1800 0.17865159
2000 0.16574495


In [51]:
hypothesis

<tf.Tensor 'Softmax_7:0' shape=(?, 3) dtype=float32>

In [69]:
x_data = [[1,2,1,1], [2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]
# one-hot encoding

X = tf.placeholder("float",[None,4])
Y = tf.placeholder("float",[None,3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(Logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax((tf.matmul(X,W)+b))

# Cross entropy cost/loss
cost= tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

        
    for step in range(2001):
        a = sess.run(hypothesis, feed_dict={X:[[1,11,7,9]]})
        if step % 200 ==0 :
            print(a, sess.run(tf.arg_max(a,1)))            


[[1.0000000e+00 8.5449785e-15 5.3058987e-08]] [0]
[[1.0000000e+00 8.5449785e-15 5.3058987e-08]] [0]
[[1.0000000e+00 8.5449785e-15 5.3058987e-08]] [0]
[[1.0000000e+00 8.5449785e-15 5.3058987e-08]] [0]
[[1.0000000e+00 8.5449785e-15 5.3058987e-08]] [0]
[[1.0000000e+00 8.5449785e-15 5.3058987e-08]] [0]
[[1.0000000e+00 8.5449785e-15 5.3058987e-08]] [0]
[[1.0000000e+00 8.5449785e-15 5.3058987e-08]] [0]
[[1.0000000e+00 8.5449785e-15 5.3058987e-08]] [0]
[[1.0000000e+00 8.5449785e-15 5.3058987e-08]] [0]
[[1.0000000e+00 8.5449785e-15 5.3058987e-08]] [0]


In [74]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for i in range(101):    
        
        all = sess.run(hypothesis, feed_dict={X:[[1,11,7,9],
                                                [1,3,4,13],
                                                [1,1,0,1]]})
        if i % 20 == 0:
            print(all, sess.run(tf.arg_max(all,1)))

[[9.9999988e-01 1.5201661e-07 1.5659664e-08]
 [1.0000000e+00 1.2732916e-12 5.1666638e-15]
 [3.9220664e-01 3.0078676e-02 5.7771468e-01]] [0 0 2]
[[9.9999988e-01 1.5201661e-07 1.5659664e-08]
 [1.0000000e+00 1.2732916e-12 5.1666638e-15]
 [3.9220664e-01 3.0078676e-02 5.7771468e-01]] [0 0 2]
[[9.9999988e-01 1.5201661e-07 1.5659664e-08]
 [1.0000000e+00 1.2732916e-12 5.1666638e-15]
 [3.9220664e-01 3.0078676e-02 5.7771468e-01]] [0 0 2]
[[9.9999988e-01 1.5201661e-07 1.5659664e-08]
 [1.0000000e+00 1.2732916e-12 5.1666638e-15]
 [3.9220664e-01 3.0078676e-02 5.7771468e-01]] [0 0 2]
[[9.9999988e-01 1.5201661e-07 1.5659664e-08]
 [1.0000000e+00 1.2732916e-12 5.1666638e-15]
 [3.9220664e-01 3.0078676e-02 5.7771468e-01]] [0 0 2]
[[9.9999988e-01 1.5201661e-07 1.5659664e-08]
 [1.0000000e+00 1.2732916e-12 5.1666638e-15]
 [3.9220664e-01 3.0078676e-02 5.7771468e-01]] [0 0 2]
